<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CashFlow.Transactions.Domain</RootNamespace>
    <AssemblyName>CashFlow.Transactions.Domain</AssemblyName>
  </PropertyGroup>

</Project>
